export const FETCH_MARKET_INFO = 'FETCH_MARKET_INFO';
export const REVEIVE_MARKET_INFO = 'REVEIVE_MARKET_INFO';

export const FETCH_NEWS_LIST = 'FETCH_NEWS_LIST';
export const REVEIVE_NEWS_LIST = 'REVEIVE_NEWS_LIST';



export const RECEIVE_TOPTEN = 'RECEIVE_TOPTEN';
export const RECEIVE_IDLIST = 'RECEIVE_IDLIST';

export const RECEIVE_HP = 'RECEIVE_HP';

export const RECEIVE_ESSAY = 'RECEIVE_ESSAY';
export const RECEIVE_SERIAL = 'RECEIVE_SERIAL';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';

export const RECEIVE_NEXTPAGE = 'RECEIVE_NEXTPAGE';

export const RECEIVE_MUSIC = 'RECEIVE_MUSIC';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_MOVIE_PHOTOS = 'RECEIVE_MOVIE_PHOTOS';

export const WEATHER = 'WEATHER';
