  // 登录
  export const LOGIN = 'LOGIN';
  export const LOGOUT = 'LOGOUT';
  // 注册
  export const REGISTER = 'REGISTER';
  export const REVEIVE_AUTH_CODE = 'REVEIVE_AUTH_CODE';
  // 首页
  export const REVEIVE_NOTICE = 'REVEIVE_NOTICE';
  export const REVEIVE_INDEX = 'REVEIVE_INDEX';
  export const REVEIVE_INDEX_DETAIL = 'REVEIVE_INDEX_DETAIL';
  export const REVEIVE_INDEX_SPECIAL = 'REVEIVE_INDEX_SPECIAL';
  // 业务
  export const REVEIVET_MY_WALLET_DETAIL = 'REVEIVET_MY_WALLET_DETAIL';
  export const REVEIVET_MY_ENTRUST_LIST = 'REVEIVET_MY_ENTRUST_LIST';
  export const REVEIVE_AVAILABLE_ENTRUST_LIST = 'REVEIVE_AVAILABLE_ENTRUST_LIST';
  export const REVEIVE_ENTRUST_DETAIL = 'REVEIVE_ENTRUST_DETAIL';
  export const BUY_ENTRUST = 'BUY_ENTRUST';
  export const CONVERT_PRICE = 'CONVERT_PRICE';
  export const QUERY_RECHARGE = 'QUERY_RECHARGE';
  export const RECHARGE = 'RECHARGE';
  // 交易
  export const REVEIVE_MARKET_INFO = 'REVEIVE_MARKET_INFO';
  // 媒体
  export const REVEIVE_NEWS_LIST = 'REVEIVE_NEWS_LIST';

  // 我的
  export const BIND_TEL_OR_EMAIL = 'BIND_TEL_OR_EMAIL';
  export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
  export const CERTIFY = 'CERTIFY';
  export const ADVANCED_CERTIFY = 'ADVANCED_CERTIFY';
